Repository FE-STUDY-2024/JS-Study, pull requests merged in 2024-04, with the labels that each got.

#1 [1주차][주하][4, 5, 6, 9, 10, 11, 12]
  1주차/주하.md
Labels: 주하

#5 [1주차][은지][4, 5, 6, 9, 10, 11, 12]
  1주차/은지.md
Labels: 은지

#3 [1주차][민규][4, 5, 6, 9, 10, 11, 12]
  1주차/민규.md
Labels: 민규

#2 [1주차][나영][4, 5, 6, 9, 10, 11, 12]
  1주차/나영.md
Labels: 나영

#4 [1주차][가현][4, 5, 6, 9, 10, 11, 12]
  1주차/가현.md
Labels: 가현

#8 [2주차][은지][13, 14, 15, 16, 17, 18]
  .idea/.gitignore
  .idea/JS-Study.iml
  .idea/modules.xml
  .idea/vcs.xml
  2주차/은지.md
Labels: 은지

#9 [2주차][주하][13, 14, 15, 16, 17, 18]
  2주차/주하.md
Labels: 주하

#6 [2주차][나영][13, 14, 15, 16, 17, 18]
  2주차/나영.md
Labels: 나영

#7 [2주차][가현][13, 14, 15, 16, 17, 18]
  2주차/가현.md
Labels: 가현

#11 [2주차][민규][13, 14, 15, 16, 17, 18]
  2주차/민규.md
Labels: 민규

#18 [3주차][주하][19, 20, 21, 22]
  3주차/주하.md
Labels: 주하

#17 [3주차][나영][19, 20, 21, 22]
  3주차/나영.md
Labels: 나영

#19 [3주차][민규][19, 20, 21, 22]
  3주차/민규.md
Labels: 민규

#16 [3주차][가현][19, 20, 21, 22]
  .gitignore
  3주차/가현.md
Labels: 가현
