Repository FE-STUDY-2024/JS-Study, pull requests merged in 2024-05, with the labels that each got.

#28 [4주차][가현][리액트 2장]
  2주차/가현.md
  4주차/가현.md
Labels: 가현

#26 [4주차][주하][리액트 2장]
  4주차/주하.md
  5주차/주하.md
Labels: 주하

#29 [4주차][민규][리액트 2장]
  4주차/민규.md
Labels: 민규

#34 [5주차][가현][리액트 3장]
  5주차/가현.md
Labels: 가현

#35 [5주차][주하][리액트 3장]
  5주차/주하.md
Labels: 주하

#33 [5주차][은지][리액트 3장]
  5주차/은지.md
Labels: 은지

#36 [5주차][민규][리액트 3장]
  5주차/민규.md
Labels: 민규

#30 [4주차][나영][리액트 2장]
  4주차/나영.md
Labels: 나영

#39 [6주차][나영][리액트 4장]
  6주차/나영.md
Labels: 나영

#37 [6주차][가현][리액트 4장]
  6주차/가현.md
Labels: 가현

#38 [6주차][민규][리액트 4장]
  6주차/민규.md
Labels: 민규
